configuracion modificar contrasena
MrCube23/BackEnd-Waddle-Beacon pull request #7
Opened 2024-07-20 15:41 UTC by GitTae

configuracion modificar contrasena funcional

2024-07-20 22:03 UTC, ForLucho commented on src/main/java/cr/ac/ucenfotec/waddle/beacon/rest/auth/AuthRestController.java
> +            return ResponseEntity.badRequest().body("{\"error\": \"User not found\"}");
Todo se ve bien, pero para el manejo de errores sería mejor utilizar un diccionario o una hashtable.

2024-07-20 22:05 UTC, ForLucho requested changes
La funcionalidad parece estar bien, pero no es necesario gestionar la modificación de la contraseña por correo electrónico. Lo más simple es validar la contraseña actual del usuario y confirmar que la nueva sea la misma en ambos campos. Algo similar a cómo se maneja la modificación de contraseña en Discord.

![6EWu0mc](https://github.com/user-attachments/assets/1819889c-d58b-4f36-9ec8-9e1148b35666)

2024-07-22 00:45 UTC, GitTae commented
Arreglos para el merge

2024-07-22 18:21 UTC, ForLucho approved these changes
La funcionalidad del backend está bien implementada y permite acceder correctamente al método de cambiar contraseña. ¡Gracias por el excelente trabajo!

2024-07-22 18:26 UTC, Niruchie approved these changes
Se verificó la implementación y funcionalidad de modificar contraseña.

2024-07-22 18:27 UTC, merged